package kr.ac.cbnu.ubigame.analyser.common;

import java.io.IOException;
import java.util.Date;

import kr.ac.cbnu.ubigame.analyser.common.crawler.AbsCrawler;
import kr.ac.cbnu.ubigame.analyser.crawler.*;



public class SimpleJournalFactory {	
	public SimpleJournalFactory(){
	
	}
	
	public AbsCrawler getPressCrawler(String press, String url, String searchword, Date finalDate) throws IOException{
		if(press.equals("더팩트"))return new TheFact(url,searchword,finalDate);
		if(press.equals("뉴스엔"))return new NewsN(url,searchword,finalDate);
		if(press.equals("MBC 뉴스"))return new MBCNews(url,searchword,finalDate);
		if(press.equals("국민일보")) return new GookMinDaily(url, searchword,finalDate);
		if(press.equals("SBS 뉴스"))return new SBSNews(url, searchword,finalDate);
		if(press.equals("코리아타임즈")) return new KoreaTimes(url, searchword,finalDate);
		if(press.equals("YTN")) return new YTN(url, searchword,finalDate);
		if(press.equals("KBS 뉴스"))return new KBSNews(url, searchword,finalDate);
		if(press.equals("뉴데일리")) return new Newdaily(url, searchword,finalDate);
		if(press.equals("OSEN")) return new Osen(url, searchword,finalDate);
		if(press.equals("경향신문")) return new GyeonghyangNews(url, searchword,finalDate);
		if(press.equals("MBN"))return new MBN(url, searchword,finalDate);
		if(press.equals("노컷뉴스"))return new NocutNews(url, searchword,finalDate);
		if(press.equals("JTBC"))return new JTBC(url, searchword,finalDate);
		if(press.equals("BBS NEWS"))return new BBSNEWS(url, searchword,finalDate);
		if(press.equals("CCTV뉴스"))return new CCTVnews(url, searchword,finalDate);
		if(press.equals("CEO스코어데일리"))return new CEOScoreDaily(url, searchword,finalDate);
		if(press.equals("CIO Korea"))return new CIOKorea(url, searchword,finalDate);
		if(press.equals("CIOBIZ+"))return new CIOBIZ(url, searchword,finalDate);
		if(press.equals("CNB뉴스"))return new CNBNews(url, searchword,finalDate);
		if(press.equals("CNB저널"))return new CNBJournal(url, searchword,finalDate);
		if(press.equals("EBN"))return new EBN(url, searchword,finalDate);
		if(press.equals("FAM타임스"))return new FAMTimes(url, searchword,finalDate);
		if(press.equals("G1"))return new G1(url, searchword,finalDate);
		if(press.equals("GQ"))return new GQ(url, searchword,finalDate);
		if(press.equals("G밸리"))return new Gvelly(url, searchword,finalDate);
		if(press.equals("IT NEWS"))return new ITNEWS(url, searchword,finalDate);
		if(press.equals("ITWorld"))return new ITWorld(url, searchword,finalDate);
		if(press.equals("IT동아"))return new ITDonga(url, searchword,finalDate);
		if(press.equals("IT조선"))return new ITJoesun(url, searchword,finalDate);
		if(press.equals("KNS뉴스통신"))return new KNSNewsCommunication(url, searchword,finalDate);
		if(press.equals("Korea IT Times"))return new KoreaItTimes(url, searchword,finalDate);
		if(press.equals("KTV국민방송"))return new KTVBroad(url, searchword,finalDate);
		if(press.equals("MTN"))return new MTN(url, searchword,finalDate);
		if(press.equals("m이코노미"))return new MEconomy(url, searchword,finalDate);
		if(press.equals("NSP통신"))return new NSPCommunication(url, searchword,finalDate);
		if(press.equals("OBS"))return new OBS(url, searchword,finalDate);
		if(press.equals("PC사랑"))return new PCLove(url, searchword,finalDate);
		if(press.equals("Queen"))return new Queen(url, searchword,finalDate);
		if(press.equals("RPM9"))return new RPM(url, searchword,finalDate);
		if(press.equals("SBS CNBC"))return new SBSCNBC(url, searchword,finalDate);
		if(press.equals("SBS funE"))return new SBSFunE(url, searchword,finalDate);
		if(press.equals("allure"))return new Allure(url, searchword,finalDate);
		if(press.equals("bnt뉴스"))return new BntNews(url, searchword,finalDate);
		if(press.equals("SBS"))return new SBS(url, searchword,finalDate);
		if(press.equals("SK와이번스"))return new SKWyvern(url, searchword,finalDate);
		if(press.equals("tbs 교통방송"))return new TBStraffic(url, searchword,finalDate);
		if(press.equals("topclass"))return new TopClass(url, searchword,finalDate);
		if(press.equals("TV리포트"))return new TVReport(url, searchword,finalDate);
		if(press.equals("TV조선"))return new TVJoesun(url, searchword,finalDate);
		if(press.equals("VOGUE"))return new VOGUE(url, searchword,finalDate);
		if(press.equals("W"))return new W(url, searchword,finalDate);
		if(press.equals("YTN라디오"))return new YTNRadio(url, searchword,finalDate);
		if(press.equals("YTN사이언스"))return new YTNScience(url, searchword,finalDate);
		if(press.equals("ZDNet Korea"))return new ZDNetKorea(url, searchword,finalDate);
		if(press.equals("가스신문"))return new GasNews(url, searchword,finalDate);
		if(press.equals("가톨릭신문"))return new CatholicNews(url, searchword,finalDate);
		if(press.equals("가톨릭평화방송·평화신문"))return new CatholicPeaceNews(url, searchword,finalDate);
		if(press.equals("강원도민일보"))return new GangwondoPeapleNews(url, searchword,finalDate);
		if(press.equals("강원신문"))return new GangwonNews(url, searchword,finalDate);
		if(press.equals("강원일보"))return new GangwonDaily(url, searchword,finalDate);
		if(press.equals("건설경제신문"))return new ConstructionEconomyNews(url, searchword,finalDate);
		if(press.equals("건설타임즈"))return new ConstructionTimes(url, searchword,finalDate);
		if(press.equals("게임메카"))return new Gamemecca(url, searchword,finalDate);
		if(press.equals("게임조선"))return new GameJoesun(url, searchword,finalDate);
		if(press.equals("게임포커스"))return new GameFocus(url, searchword,finalDate);
		if(press.equals("경기신문"))return new Gyeonggi(url, searchword,finalDate);
		if(press.equals("경기일보"))return new GyeonggiDaily(url, searchword,finalDate);
		if(press.equals("경남도민신문"))return new GyeongnamPeopleNews(url, searchword,finalDate);
		if(press.equals("경남도민일보"))return new GyeongnamPeopleDaily(url, searchword,finalDate);
		if(press.equals("경남매일신문"))return new GyeongnamDailyNews(url, searchword,finalDate);
		if(press.equals("경남신문"))return new GyeongnamNews(url, searchword,finalDate);
		if(press.equals("경남일보"))return new GyeongnamDaily(url, searchword,finalDate);
		if(press.equals("경북도민신문"))return new GyeongbukPeopleNews(url, searchword,finalDate);
		if(press.equals("경북도민일보"))return new GyeongbukPeopleDaily(url, searchword,finalDate);
		if(press.equals("경북매일신문"))return new GyeongbukDailyNews(url, searchword,finalDate);
		if(press.equals("경북일보"))return new GyeongbukDaily(url, searchword,finalDate);
		if(press.equals("경상매일신문"))return new GyeongsangDailyNews(url, searchword,finalDate);
		if(press.equals("경상일보"))return new GyeongsangDaily(url, searchword,finalDate);
		if(press.equals("경인일보"))return new GyeonginDaily(url, searchword,finalDate);
		if(press.equals("공감신문"))return new SympathyNews(url, searchword,finalDate);
		if(press.equals("광고없는언론 팩트올"))return new NonAdvertisementFactAll(url, searchword,finalDate);
		if(press.equals("광남일보"))return new GwangnamDaily(url, searchword,finalDate);
		if(press.equals("광주드림"))return new GwangjuDream(url, searchword,finalDate);
		if(press.equals("광주매일신문"))return new GwangjuDailyNews(url, searchword,finalDate);
		if(press.equals("광주일보"))return new GwangjuDaily(url, searchword,finalDate);
		if(press.equals("교통신문"))return new TrafficNews(url, searchword,finalDate);
		if(press.equals("국방일보"))return new SoldierDaily(url, searchword,finalDate);
		if(press.equals("국제뉴스"))new NationalNews(url, searchword,finalDate);
		if(press.equals("국제섬유튜스"))return new NationalFiberNews(url, searchword,finalDate);
		if(press.equals("국제신문"))return new NationalNewspaper(url, searchword,finalDate);
		if(press.equals("국토신문"))return new DonationsoilNews(url, searchword,finalDate);
		if(press.equals("국회"))return new Congress(url, searchword,finalDate);
		if(press.equals("굿모닝충청"))return new GoodmorningChungcheong(url, searchword,finalDate);
		if(press.equals("그린데일리"))return new GreenDaily(url, searchword,finalDate);
		if(press.equals("그린포스트코리아"))return new GreenPostKorea(url, searchword,finalDate);
		if(press.equals("글로벌경제"))return new GlobalEconomy(url, searchword,finalDate);
		if(press.equals("글로벌이코노믹"))return new GlobalEconomic(url, searchword,finalDate);
		if(press.equals("금강일보"))return new GeumgangDaily(url, searchword,finalDate);
		if(press.equals("기호일보"))return new GihoDaily(url, searchword,finalDate);
		if(press.equals("김해뉴스"))return new GimhaeNews(url, searchword,finalDate);
		if(press.equals("내일신문"))return new TomorrowNews(url, searchword,finalDate);
		if(press.equals("넥스트데일리"))return new NextDaily(url, searchword,finalDate);
		if(press.equals("녻색경제신문"))return new GreenEconomyNews(url, searchword,finalDate);
		if(press.equals("농민신문"))return new FarmerNews(url, searchword,finalDate);
		if(press.equals("농수축산신문"))return new AgricultureFishingLivestockNews(url, searchword,finalDate);
		if(press.equals("농촌여성신문"))return new RuralWomanNews(url, searchword,finalDate);
		if(press.equals("뉴스1"))return new NewsOne(url, searchword,finalDate);
		if(press.equals("뉴스메이커")) return new NewsMaker(url, searchword,finalDate);
		if(press.equals("환경일보"))return new EnviromentDaily(url, searchword,finalDate);
		if(press.equals("환경미디어"))return new EnvironmentMedia(url, searchword,finalDate);
		if(press.equals("화이트페이퍼"))return new WhitePaper(url, searchword,finalDate);
		if(press.equals("현대경제신문"))return new HyundaiEconomyNews(url, searchword,finalDate);
		if(press.equals("뉴스인사이드"))return new NewsInSide(url, searchword,finalDate);
		if(press.equals("뉴스타운"))return new NewsTown(url, searchword,finalDate);
		if(press.equals("뉴스토마토"))return new NewsTomato(url, searchword,finalDate); // 검토하기
		if(press.equals("뉴스페이퍼"))return new NewsPaper(url, searchword,finalDate);
		if(press.equals("뉴스포스트"))return new NewsPost(url, searchword,finalDate);
		if(press.equals("뉴스핌"))return new NewsPim(url, searchword,finalDate); // 검토하기
		if(press.equals("뉴스코리아"))return new NewsKorea(url, searchword,finalDate);
		if(press.equals("뉴시스"))return new Newsis(url, searchword,finalDate); // 검토하기
		if(press.equals("대구MBC"))return new DaeGuMBC(url, searchword,finalDate);
		if(press.equals("대구뉴스"))return new DaeGuNews(url, searchword,finalDate); // 검토하기
		if(press.equals("대구일보"))return new DaeGuDaily(url, searchword,finalDate); // 검토
		if(press.equals("대전시티저널"))return new DaeJeonCityJournal(url, searchword,finalDate);
		if(press.equals("대전일보"))return new DaeJeonDaily(url, searchword,finalDate); // 검토
		if(press.equals("대전투데이"))return new DaeJeonToday(url, searchword,finalDate); // 검토
		if(press.equals("대한금융신문"))return new DaeHanFinanceNews(url, searchword,finalDate); // 검토
		if(press.equals("대한변협신문"))return new DaeHanBunNews(url, searchword,finalDate);
		if(press.equals("더기어"))return new TheGear(url, searchword,finalDate);
		if(press.equals("더벨"))return new TheBell(url, searchword,finalDate);
		if(press.equals("더스쿠프"))return new TheScoop(url, searchword,finalDate);
		if(press.equals("더피알"))return new ThePR(url, searchword,finalDate);
		if(press.equals("데이터넷"))return new DataNet(url, searchword,finalDate);
		if(press.equals("데이터뉴스"))return new DataNews(url, searchword,finalDate);
		if(press.equals("데일리e스포츠"))return new DailyEsports(url, searchword,finalDate);
		if(press.equals("데일리그리드"))return new DailyGrid(url, searchword,finalDate);
		if(press.equals("데일리메디"))return new DailyMedi(url, searchword,finalDate);
		if(press.equals("데일리시큐"))return new DailySecu(url, searchword,finalDate);
		if(press.equals("데일리안"))return new Dailian(url, searchword,finalDate);
		if(press.equals("데일리팜"))return new DailyPharm(url, searchword,finalDate);
		if(press.equals("데일리한국"))return new DailyHanKook(url, searchword,finalDate);
		if(press.equals("독서신문"))return new ReadersNews(url, searchword,finalDate);
		if(press.equals("동아사이언스"))return new DongaScience(url, searchword,finalDate);
		if(press.equals("동아오토"))return new DongaAuto(url, searchword,finalDate);
		if(press.equals("동아일보"))return new DongaDaily(url, searchword,finalDate);
		if(press.equals("동양일보"))return new DongyangDaily(url, searchword,finalDate);
		if(press.equals("디스이즈게임"))return new ThisIsGame(url, searchword,finalDate);
		if(press.equals("디아이투데이"))return new DiToday(url, searchword,finalDate);
		if(press.equals("디자인정글"))return new DesignJungle(url, searchword,finalDate);
		if(press.equals("디지털데일리"))return new DigitalDaily(url, searchword,finalDate);
		if(press.equals("디지털타임스"))return new DigitalTimes(url, searchword,finalDate);
		if(press.equals("디트뉴스24"))return new DiteNews24(url, searchword,finalDate);
		if(press.equals("딜라이트닷넷"))return new DelightNet(url, searchword,finalDate);
		if(press.equals("딴지일보"))return new DdanjiDaily(url, searchword,finalDate);
		if(press.equals("라디오코리아"))return new RadioKorea(url, searchword,finalDate);
		if(press.equals("라포르시안"))return new Rapportian(url, searchword,finalDate);
		if(press.equals("로봇신문"))return new RobotNews(url, searchword,finalDate);
		if(press.equals("로이슈"))return new Lawissue(url, searchword,finalDate);
		if(press.equals("루키"))return new Rookie(url, searchword,finalDate);
		if(press.equals("르몽드"))return new Lemonde(url, searchword,finalDate);
		if(press.equals("마이데일리"))return new MyDaily(url, searchword,finalDate);
		if(press.equals("매경이코노미"))return new MkEconomy(url, searchword,finalDate);
		if(press.equals("매일경제"))return new DailyEconomy(url, searchword,finalDate);
		if(press.equals("매일경제24"))return new DailyEconomy24(url, searchword,finalDate);
		if(press.equals("매일노동뉴스"))return new DailyWorkNews(url, searchword,finalDate);
		if(press.equals("매일신문"))return new DailyNews(url, searchword,finalDate);
		if(press.equals("매일일보"))return new EverydayDaily(url, searchword,finalDate);
		if(press.equals("맥스무비"))return new MaxMovie(url, searchword,finalDate);
		if(press.equals("머니S"))return new MoneyS(url, searchword,finalDate);
		if(press.equals("머니투데이"))return new MoneyToday(url, searchword,finalDate);
		if(press.equals("메디게이트뉴스"))return new MediGateNews(url, searchword,finalDate);
		if(press.equals("메디컬업저버"))return new MedicalObserver(url, searchword,finalDate);
		if(press.equals("메디컬타임즈"))return new MedicalTimes(url, searchword,finalDate);
		if(press.equals("메디컬투데이"))return new MedicalToday(url, searchword,finalDate);
		if(press.equals("메디파나뉴스"))return new Medipana(url, searchword,finalDate);
		if(press.equals("메트로뉴스"))return new MetroNews(url, searchword,finalDate);
		if(press.equals("몬스터짐"))return new MonsterZym(url, searchword,finalDate);
		if(press.equals("무등일보"))return new MooDeungNews(url, searchword,finalDate);
		if(press.equals("무비조이"))return new MovieJoy(url, searchword,finalDate);
		if(press.equals("문화뉴스"))return new CultureNews(url, searchword,finalDate);
		if(press.equals("문화일보"))return new CultureDaily(url, searchword,finalDate);
		if(press.equals("문화저널21"))return new CultureJournal24(url, searchword,finalDate);
		if(press.equals("물류신문"))return new Distribution(url, searchword,finalDate);
		if(press.equals("미디어스"))return new Medias(url, searchword,finalDate);
		if(press.equals("미디어오늘"))return new MeidaToday(url, searchword,finalDate);
		if(press.equals("미디어워치"))return new MediaWatch(url, searchword,finalDate);
		if(press.equals("미디어펜"))return new MediaPen(url, searchword,finalDate);
		if(press.equals("미래한국"))return new FutureKorea(url, searchword,finalDate);
		if(press.equals("미주중앙일보"))return new MJMiddleDaily(url, searchword,finalDate);
		if(press.equals("미주한국일보"))return new MJKoreaDaily(url, searchword,finalDate);
		if(press.equals("민중의소리"))return new PeopleVoice(url, searchword,finalDate);
		if(press.equals("법률신문"))return new LegalNews(url, searchword,finalDate);
		if(press.equals("법률저널"))return new LegalJournal(url, searchword,finalDate);
		if(press.equals("법보신문"))return new BubboNews(url, searchword,finalDate);
		if(press.equals("베리타스알파"))return new VeritasAlpha(url, searchword,finalDate);
		if(press.equals("베이비뉴스"))return new BabyNews(url, searchword,finalDate);
		if(press.equals("베타뉴스"))return new BetaNews(url, searchword,finalDate);
		if(press.equals("보안뉴스"))return new SecurityNews(url, searchword,finalDate);
		if(press.equals("부산일보"))return new BusanDaily(url, searchword,finalDate);
		if(press.equals("불교공뉴스"))return new BuddhismNews(url, searchword,finalDate);
		if(press.equals("불교닷컴"))return new BuddhismDotCom(url, searchword,finalDate);
		if(press.equals("불교신문"))return new BuddhismDaily(url, searchword,finalDate);
		if(press.equals("뷰스앤뉴스"))return new ViewsAndNews(url, searchword,finalDate);
		if(press.equals("브레이크뉴스"))return new BreakNews(url, searchword,finalDate);
		if(press.equals("브레인미디어"))return new BrainMedia(url, searchword,finalDate);
		if(press.equals("브레인박스벤치마크"))return new BrainBoxBenchMark(url, searchword,finalDate);
		if(press.equals("브릿지경제"))return new BridgeEconomy(url, searchword,finalDate);
		if(press.equals("블로터"))return new Bloter(url, searchword,finalDate);
		if(press.equals("비주얼다이브"))return new VisualDive(url, searchword,finalDate);
		if(press.equals("비즈니스워치"))return new BusinessWatch(url, searchword,finalDate);
		if(press.equals("비즈니스포스트"))return new BusinessPost(url, searchword,finalDate);
		if(press.equals("비즈엔터"))return new BizEnter(url, searchword,finalDate);
		if(press.equals("비즈트리뷴"))return new BizTriBune(url, searchword,finalDate);
		if(press.equals("산업일보"))return new IndustryDaily(url, searchword,finalDate);
		if(press.equals("새전북신문"))return new NewJunBukNews(url, searchword,finalDate);
		if(press.equals("서울경제"))return new SeoulEconomy(url, searchword,finalDate);
		if(press.equals("서울신문"))return new SeoulNews(url, searchword,finalDate);
		if(press.equals("서울파이낸스"))return new SeoulFinance(url, searchword,finalDate);
		if(press.equals("세계일보"))return new WorldDaily(url, searchword,finalDate);
		if(press.equals("세정일보"))return new SejungDaily(url, searchword,finalDate);
		if(press.equals("세종포스트"))return new SejongPost(url, searchword,finalDate);
		if(press.equals("소년한국일보"))return new BoyKoreaDaily(url, searchword,finalDate);
		if(press.equals("소믈리에타임즈"))return new SommelierTimes(url, searchword,finalDate);
		if(press.equals("소방방재신문"))return new FirefightingNews(url, searchword,finalDate);
		if(press.equals("소비자가만드는신문"))return new ConsumerMakesNews(url, searchword,finalDate);
		if(press.equals("손대범칼럼"))return new SonDaeBumColumn(url, searchword,finalDate);
		if(press.equals("수원일보"))return new SuwonDaily(url, searchword,finalDate);
		if(press.equals("슈어"))return new Sure(url, searchword,finalDate);
		if(press.equals("스냅"))return new Snap(url, searchword,finalDate);
		if(press.equals("스틸앤메탈뉴스"))return new StealAndMetalNews(url, searchword,finalDate);
		if(press.equals("스페셜경제"))return new SpecialEconomy(url, searchword,finalDate);
		if(press.equals("스포츠Q"))return new SportsQ(url, searchword,finalDate);
		if(press.equals("스포츠경향"))return new SportsTrend(url, searchword,finalDate);
		if(press.equals("스포츠동아"))return new SportsDonga(url, searchword,finalDate);
		if(press.equals("스포츠서울"))return new SportsSeoul(url, searchword,finalDate);
		if(press.equals("스포츠월드"))return new SportsWorld(url, searchword,finalDate);
		if(press.equals("스포츠조선"))return new SportsJosun(url, searchword,finalDate);
		if(press.equals("스포츠투데이"))return new SportsToday(url, searchword,finalDate);
		if(press.equals("스포츠한국"))return new SportsKorea(url, searchword,finalDate);
		if(press.equals("스포티비뉴스"))return new SpotvNews(url, searchword,finalDate);
		if(press.equals("슬로우뉴스"))return new SlowNews(url, searchword,finalDate);
		if(press.equals("시민일보"))return new CitizenNews(url, searchword,finalDate);
		if(press.equals("시사IN"))return new SisaIn(url, searchword,finalDate);
		if(press.equals("시사오늘"))return new SisaToday(url, searchword,finalDate);
		if(press.equals("시사위크"))return new SisaWeek(url, searchword,finalDate);
		if(press.equals("시사저널"))return new SisaJournal(url, searchword,finalDate);
		if(press.equals("시사저널이코노미"))return new SisaJournalEconomy(url, searchword,finalDate);
		if(press.equals("시사제주"))return new SisaJeju(url, searchword,finalDate);
		if(press.equals("시사포커스"))return new SisaFocus(url, searchword,finalDate);
		if(press.equals("시선뉴스"))return new SisunNews(url, searchword,finalDate);
		if(press.equals("시크뉴스"))return new SeekNews(url, searchword,finalDate);
		if(press.equals("신동아"))return new NewDonga(url, searchword,finalDate);
		if(press.equals("신아일보"))return new SinaDaily(url, searchword,finalDate);
		if(press.equals("쎄씨"))return new Ssessi(url, searchword,finalDate);
		if(press.equals("씨네21"))return new Cine21(url, searchword,finalDate);
		if(press.equals("씨넷코리아"))return new CnetKorea(url, searchword,finalDate);
		if(press.equals("아시아경제"))return new AsiaEconomy(url, searchword,finalDate);
		if(press.equals("아시아뉴스통신"))return new AsiaNewsCommunicate(url, searchword,finalDate);
		if(press.equals("아시아엔"))return new AsiaN(url, searchword,finalDate);
		if(press.equals("아시아투데이"))return new AsiaToday(url, searchword,finalDate);
		if(press.equals("아이뉴스24"))return new INews24(url, searchword,finalDate);
		if(press.equals("아이즈"))return new Ize(url, searchword,finalDate);
		if(press.equals("아이티데일리"))return new ITDaily(url, searchword,finalDate);
		if(press.equals("아주경제"))return new AjuEconomy(url, searchword,finalDate);
		if(press.equals("아크로펜"))return new AcroPen(url, searchword,finalDate);
		if(press.equals("약사공론"))return new PharmacistNews(url, searchword,finalDate);
		if(press.equals("약업신문"))return new PharmacistDaily(url, searchword,finalDate);
		if(press.equals("어패럴뉴스"))return new ApparelNews(url, searchword,finalDate);
		if(press.equals("업코리아"))return new UpKorea(url, searchword,finalDate);
		if(press.equals("에너지경제"))return new EnergyEconomy(url, searchword,finalDate);
		if(press.equals("에듀동아"))return new EduDonga(url, searchword,finalDate);
		if(press.equals("에이블뉴스"))return new AbleNews(url, searchword,finalDate);
		if(press.equals("에이빙뉴스"))return new AbingNews(url, searchword,finalDate);
		if(press.equals("엑스포츠뉴스"))return new XportsNews(url, searchword,finalDate);
		if(press.equals("엔지니어링데일리"))return new EngineeringDaily(url, searchword,finalDate);
		if(press.equals("엔터미디어"))return new EnterMedia(url, searchword,finalDate);
		if(press.equals("엠스플뉴스"))return new MsPleNews(url, searchword,finalDate);
		if(press.equals("여성신문"))return new WomanNews(url, searchword,finalDate);
		if(press.equals("연합뉴스"))return new YonhapNews(url, searchword,finalDate);
		if(press.equals("연합뉴스TV"))return new YonhapNewsTv(url, searchword,finalDate);
		if(press.equals("연합인포맥스"))return new YonhapInfoMax(url, searchword,finalDate);
		if(press.equals("영남일보"))return new YoungnamDaily(url, searchword,finalDate);
		if(press.equals("오마이뉴스"))return new OhMyNews(url, searchword,finalDate);
		if(press.equals("오토타임즈"))return new AutoTimes(url, searchword,finalDate);
		if(press.equals("울산매일신문"))return new UlsanEverydayNews(url, searchword,finalDate);
		if(press.equals("울산저널"))return new UlsanJournal(url, searchword,finalDate);
		if(press.equals("울산종합일보"))return new UlsanTotalNews(url, searchword,finalDate);
		if(press.equals("월간마이더스"))return new MonthMidus(url, searchword,finalDate);
		if(press.equals("월간암"))return new MonthArm(url, searchword,finalDate);
		if(press.equals("월간중앙"))return new MonthCenter(url, searchword,finalDate);
		if(press.equals("월간현대경영"))return new MonthHyundaiManage(url, searchword,finalDate);
		if(press.equals("위클리오늘"))return new WeeklyToday(url, searchword,finalDate);
		if(press.equals("위키트리"))return new WikiTree(url, searchword,finalDate);
		if(press.equals("윈터뉴스코리아"))return new WinterNewsKorea(url, searchword,finalDate);
		if(press.equals("유교신문"))return new YukyoNews(url, searchword,finalDate);
		if(press.equals("의학신문"))return new MedicalNews(url, searchword,finalDate);
		if(press.equals("의협신문"))return new DoctorNews(url, searchword,finalDate);
		if(press.equals("이뉴스투데이"))return new EnewsToday(url, searchword,finalDate);
		if(press.equals("이데일리"))return new Edaily(url, searchword,finalDate);
		if(press.equals("이코노미조선"))return new EconomyJosun(url, searchword,finalDate);
		if(press.equals("이코노미톡뉴스"))return new EconomyTalkNews(url, searchword,finalDate);
		if(press.equals("이코노믹리뷰"))return new EconomicReview(url, searchword,finalDate);
		if(press.equals("이투뉴스"))return new EtoNews(url, searchword,finalDate);
		if(press.equals("이투데이"))return new EToday(url, searchword,finalDate);
		if(press.equals("인벤"))return new Inven(url, searchword,finalDate);
		if(press.equals("인천일보"))return new IncheonDaily(url, searchword,finalDate);
		if(press.equals("일간NTN"))return new DailyNTN(url, searchword,finalDate);
		if(press.equals("일다"))return new Ilda(url, searchword,finalDate);
		if(press.equals("일요서울"))return new SundaySeoul(url, searchword,finalDate);
		if(press.equals("일요시사"))return new SundaySisa(url, searchword,finalDate);
		if(press.equals("일요신문"))return new SundayNews(url, searchword,finalDate);
		if(press.equals("자유한국당"))return new FreedomKorea(url, searchword,finalDate);
		if(press.equals("장애인신문"))return new DisabledNews(url, searchword,finalDate);
		if(press.equals("재외동포신문"))return new OverseasKoreanNews(url, searchword,finalDate);
		if(press.equals("전기신문"))return new ElectricNews(url, searchword,finalDate);
		if(press.equals("전남일보"))return new JunNamDaily(url, searchword,finalDate);
		if(press.equals("전라일보"))return new JunLaDaily(url, searchword,finalDate);
		if(press.equals("전민일보"))return new JunMinDaily(url, searchword,finalDate);
		if(press.equals("전북도민일보"))return new JunBukDaily(url, searchword,finalDate);
		if(press.equals("전북일보"))return new JunBukNews(url, searchword,finalDate);
		if(press.equals("전업농신문"))return new Palnews(url, searchword,finalDate);
		if(press.equals("전자신문"))return new ElectroNews(url, searchword,finalDate);
		if(press.equals("점프볼"))return new JumpBall(url, searchword,finalDate);
		if(press.equals("정책브리핑"))return new PolicyBriefing(url, searchword,finalDate);
		if(press.equals("제민일보"))return new JeminDaily(url, searchword,finalDate);
		if(press.equals("제주도민일보"))return new JejudoDaily(url, searchword,finalDate);
		if(press.equals("제주신보"))return new JujuSinbo(url, searchword,finalDate);
		if(press.equals("제주의소리"))return new JejuVoice(url, searchword,finalDate);
		if(press.equals("조선비즈"))return new JosunBiz(url, searchword,finalDate);
		if(press.equals("조선일보"))return new JosunDaily(url, searchword,finalDate);
		if(press.equals("조선펍"))return new JosunPup(url, searchword,finalDate);
		if(press.equals("조세금융신문"))return new JoseFinanceNews(url, searchword,finalDate);
		if(press.equals("조세일보"))return new JoseDaily(url, searchword,finalDate);
		if(press.equals("주간경향"))return new WeeklyTendency(url, searchword,finalDate);
		if(press.equals("주간동아"))return new WeeklyDonga(url, searchword,finalDate);
		if(press.equals("중기이코노미"))return new MiddleEconomy(url, searchword,finalDate);
		if(press.equals("중도일보"))return new MiddleDaily(url, searchword,finalDate);
		if(press.equals("중부매일"))return new JungBuEveryday(url, searchword,finalDate);
		if(press.equals("중부일보"))return new JungBuDaily(url, searchword,finalDate);
		if(press.equals("중소기업뉴스"))return new SmallBusiniessesNews(url, searchword,finalDate);
		if(press.equals("중소기업신문"))return new SmallBusiniessesDaily(url, searchword,finalDate);
		if(press.equals("중앙SUNDAY"))return new MiddleSunday(url, searchword,finalDate);
		if(press.equals("중앙일보"))return new JungAngDaily(url, searchword,finalDate);
		if(press.equals("지피코리아"))return new JippyKorea(url, searchword,finalDate);
		if(press.equals("참여와혁신"))return new JoinAndInovation(url, searchword,finalDate);
		if(press.equals("채널A"))return new ChannelA(url, searchword,finalDate);
		if(press.equals("채널예스"))return new ChannelYes(url, searchword,finalDate);
		if(press.equals("천지일보"))return new ChunjiDaily(url, searchword,finalDate);
		if(press.equals("청년의사"))return new YouthDoctor(url, searchword,finalDate);
		if(press.equals("청와대"))return new Cheongwadae(url, searchword,finalDate);
		if(press.equals("초이스경제"))return new ChoiceEconomy(url, searchword,finalDate);
		if(press.equals("충남일보"))return new ChungNamDaily(url, searchword,finalDate);
		if(press.equals("충북일보"))return new ChungBukDaily(url, searchword,finalDate);
		if(press.equals("충청매일"))return new ChungCheongDaily(url, searchword,finalDate);
		if(press.equals("충청일보"))return new ChungCheongNews(url, searchword,finalDate);
		if(press.equals("충청타임즈"))return new ChungCheongTimes(url, searchword,finalDate);
		if(press.equals("충청투데이"))return new ChungCheongToday(url, searchword,finalDate);
		if(press.equals("캠퍼스잡앤조이"))return new CampusjobAndJoy(url, searchword,finalDate);
		if(press.equals("컨슈머타임스"))return new ConsumerTimes(url, searchword,finalDate);
		if(press.equals("케이벤치"))return new KBench(url, searchword,finalDate);
		if(press.equals("코리아쉬핑가제트"))return new KoreaSweepingGazette(url, searchword,finalDate);
		if(press.equals("코리아타임스"))return new KoreaTimes(url, searchword,finalDate);
		if(press.equals("코리아헤럴드"))return new KoreaHerald(url, searchword,finalDate);
		if(press.equals("코리아헬스로그"))return new KoreaHealthLog(url, searchword,finalDate);
		if(press.equals("쿠키뉴스"))return new CookieNews(url, searchword,finalDate);
		if(press.equals("키뉴스"))return new KeyNews(url, searchword,finalDate);
		if(press.equals("키즈맘"))return new KidsMom(url, searchword,finalDate);
		if(press.equals("테크M"))return new TechM(url, searchword,finalDate);
		if(press.equals("테크노아"))return new TechNoa(url, searchword,finalDate);
		if(press.equals("테크홀릭"))return new TechHolic(url, searchword,finalDate);
		if(press.equals("텐아시아"))return new TenAsia(url, searchword,finalDate);
		if(press.equals("톱스타뉴스"))return new TopstarNews(url, searchword,finalDate);
		if(press.equals("통일신문"))return new UnificationNews(url, searchword,finalDate);
		if(press.equals("투데이에너지"))return new TodayEnergy(url, searchword,finalDate);
		if(press.equals("트래블바이크뉴스"))return new TravelBikeNews(url, searchword,finalDate);
		if(press.equals("티브이데일리"))return new TVDaily(url, searchword,finalDate);
		if(press.equals("ㅍㅍㅅㅅ"))return new Ppss(url, searchword,finalDate);
		if(press.equals("파운드매거진"))return new FoundMagazine(url, searchword,finalDate);
		if(press.equals("파이낸셜뉴스"))return new FinacialNews(url, searchword,finalDate);
		if(press.equals("팝뉴스"))return new PopNews(url, searchword,finalDate);
		if(press.equals("패션비즈"))return new FashionBiz(url, searchword,finalDate);
		if(press.equals("패션엔"))return new FashionN(url, searchword,finalDate);
		if(press.equals("패션저널"))return new FashionJournal(url, searchword,finalDate);
		if(press.equals("포모스"))return new Fomos(url, searchword,finalDate);
		if(press.equals("포브스코리아"))return new ForbesKorea(url, searchword,finalDate);
		if(press.equals("폴리뉴스"))return new PolyNews(url, searchword,finalDate);
		if(press.equals("풋볼리스트"))return new FootballList(url, searchword,finalDate);
		if(press.equals("프라임경제"))return new PrimeEconomy(url, searchword,finalDate);
		if(press.equals("프레시안"))return new Pressian(url, searchword,finalDate);
		if(press.equals("플래텀"))return new Platum(url, searchword,finalDate);
		if(press.equals("한강타임즈"))return new HanRiverTimes(url, searchword,finalDate);
		if(press.equals("한겨레"))return new Hani(url, searchword,finalDate);
		if(press.equals("한겨레21"))return new Hani21(url, searchword,finalDate);
		if(press.equals("환경비즈니스"))return new EnvironmentBusiness(url, searchword,finalDate);
		if(press.equals("한국경제"))return new KoreaEconomy(url, searchword,finalDate);
		if(press.equals("한국경제TV"))return new KoreaEconomyTV(url, searchword,finalDate);
		if(press.equals("한국교육신문"))return new KoreaEducationNews(url, searchword,finalDate);
		if(press.equals("한국금융신문"))return new KoreaFinanceNews(url, searchword,finalDate);
		if(press.equals("한국농어민신문"))return new KoreaFamerNews(url, searchword,finalDate);
		if(press.equals("한국농업신문"))return new KoreaFarmingNews(url, searchword,finalDate);
		if(press.equals("한국대학신문"))return new KoreaCollegeNews(url, searchword,finalDate);
		if(press.equals("한국무역신문"))return new KoreaTradeNews(url, searchword,finalDate);
		if(press.equals("한국보험신문"))return new KoreaInsuranceNews(url, searchword,finalDate);
		if(press.equals("한국섬유신문"))return new KoreaFiberNews(url, searchword,finalDate);
		if(press.equals("한국스포츠경제"))return new KoreaSportsEconomy(url, searchword,finalDate);
		if(press.equals("한국일보"))return new KoreaDaily(url, searchword,finalDate);
		if(press.equals("한국정경신문"))return new KoreaPolicyEconomyNews(url, searchword,finalDate);
		if(press.equals("한국정책신문"))return new KoreaPolicyNews(url, searchword,finalDate);
		if(press.equals("한라일보"))return new HanlaDaily(url, searchword,finalDate);
		if(press.equals("함께걸음"))return new TogetherWalk(url, searchword,finalDate);
		if(press.equals("허드포스트코리아"))return new HudPostKorea(url, searchword,finalDate);
		if(press.equals("헤드라인제주"))return new HeadlineJeju(url, searchword,finalDate);
		if(press.equals("헤럴드POP"))return new HeraldPOP(url, searchword,finalDate);
		if(press.equals("헤럴드경제"))return new HeraldEconomy(url, searchword,finalDate);
		if(press.equals("핼로디디"))return new HelloDd(url, searchword,finalDate);
		if(press.equals("핼로티"))return new HelloT(url, searchword,finalDate);
		if(press.equals("헬스조선"))return new HealthJosun(url, searchword,finalDate);
		return null;	

	}
}

